language: c

before_install:
    # update package list
    - sudo apt-get update -qq

install:
    # install packages needed for mk-build-deps
    - sudo apt-get install -qq --no-install-recommends devscripts equivs
    # pull build deps from debian/control
    - sudo mk-build-deps -ir
    # remove packages needed for mk-build-deps
    - sudo apt-get purge -qq equivs
    - sudo apt-get autoremove -qq

before_script:
    # download original and repack tarball
    - VER=$(head -1 debian/changelog | awk -F'[()]' '{print $2}' | awk -F'+' '{print $1}'); wget http://www.rfxn.com/downloads/maldetect-${VER}.tar.gz -O ../maldetect_${VER}.orig.tar.gz && ./debian/bin/repack.sh ../maldetect_${VER}.orig.tar.gz

script:
    # build the debian package
    - debuild -uc -us

after_script:
    # run lintian after build
    - sudo apt-get install -qq --no-install-recommends lintian
    - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc
#notifications:
#  email: false
